package net.ripster.mobile.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * Палитры — СГЕНЕРИРОВАНЫ из static/css/main.css десктопного Ripster,
 * не переписаны руками.
 *
 * Смысл в том, что телефон и десктоп обязаны иметь один контракт цвета.
 * Переписывание руками — это ровно тот способ, которым темы разъехались в вебе:
 * 16 провалов контраста из 60 проверок, потому что каждая новая тема была
 * «скопируй и поправь что вспомнишь».
 *
 * Проверка та же: tools/check_contrast.py. Если правишь здесь — правь в CSS
 * и перегенерируй, иначе два дерева снова начнут расходиться.
 */

data class RipsterColors(
    val surface_canvas: Color,
    val surface_sunken: Color,
    val surface_raised: Color,
    val surface_overlay: Color,
    val surface_hover: Color,
    val surface_active: Color,
    val text_primary: Color,
    val text_secondary: Color,
    val text_tertiary: Color,
    val text_disabled: Color,
    val text_on_fill: Color,
    val border_subtle: Color,
    val border_default: Color,
    val border_strong: Color,
    val focus_ring: Color,
    val success_text: Color,
    val success_fill: Color,
    val warning_text: Color,
    val warning_fill: Color,
    val danger_text: Color,
    val danger_fill: Color,
    val progress_text: Color,
    val progress_fill: Color,
    val info_text: Color,
    val info_fill: Color,
    val accent_text: Color,
    val accent_fill: Color,
    val accent_hover: Color,
    val accent_active: Color,
)

val DarkColors = RipsterColors(
    surface_canvas = Color(0xFF111318),
    surface_sunken = Color(0xFF0D0F13),
    surface_raised = Color(0xFF1C1E2A),
    surface_overlay = Color(0xFF252836),
    surface_hover = Color(0xFF2A2A3A),
    surface_active = Color(0xFF232531),
    text_primary = Color(0xFFE8E8F8),
    text_secondary = Color(0xFFA8A8C0),
    text_tertiary = Color(0xFF9494AE),
    text_disabled = Color(0xFF6A6A84),
    text_on_fill = Color(0xFF0D0F13),
    border_subtle = Color(0xFF2A2C3C),
    border_default = Color(0xFF3A3A58),
    border_strong = Color(0xFF6E6E94),
    focus_ring = Color(0xFF7AA8FF),
    success_text = Color(0xFF3ECFAA),
    success_fill = Color(0xFF2FB894),
    warning_text = Color(0xFFFFD60A),
    warning_fill = Color(0xFFE0A800),
    danger_text = Color(0xFFFF6B64),
    danger_fill = Color(0xFFE05A52),
    progress_text = Color(0xFF4DA3FF),
    progress_fill = Color(0xFF2F7FD8),
    info_text = Color(0xFF9AA0D8),
    info_fill = Color(0xFF7A80C0),
    accent_text = Color(0xFFC084A0),
    accent_fill = Color(0xFFA86A88),
    accent_hover = Color(0xFFB87C9A),
    accent_active = Color(0xFFA87490),
)

val LightColors = RipsterColors(
    surface_canvas = Color(0xFFF4F4F8),
    surface_sunken = Color(0xFFEBEBF0),
    surface_raised = Color(0xFFFFFFFF),
    surface_overlay = Color(0xFFF0F0F5),
    surface_hover = Color(0xFFEFEFF4),
    surface_active = Color(0xFFE8E8EE),
    text_primary = Color(0xFF18181F),
    text_secondary = Color(0xFF4A4A5C),
    text_tertiary = Color(0xFF5D5D70),
    text_disabled = Color(0xFF8A8A9A),
    text_on_fill = Color(0xFFFFFFFF),
    border_subtle = Color(0x12000000),
    border_default = Color(0x24000000),
    border_strong = Color(0x75000000),
    focus_ring = Color(0xFF0060D0),
    success_text = Color(0xFF0F7233),
    success_fill = Color(0xFF0F7233),
    warning_text = Color(0xFF8A5A00),
    warning_fill = Color(0xFFB5730D),
    danger_text = Color(0xFFC0281F),
    danger_fill = Color(0xFFC0281F),
    progress_text = Color(0xFF0060D0),
    progress_fill = Color(0xFF0060D0),
    info_text = Color(0xFF5A4FB0),
    info_fill = Color(0xFF5A4FB0),
    accent_text = Color(0xFF9C4F78),
    accent_fill = Color(0xFF9C4F78),
    accent_hover = Color(0xFF8C4569),
    accent_active = Color(0xFF7A3A5A),
)

val MidnightColors = RipsterColors(
    surface_canvas = Color(0xFF000000),
    surface_sunken = Color(0xFF050506),
    surface_raised = Color(0xFF0C0C0F),
    surface_overlay = Color(0xFF15151A),
    surface_hover = Color(0xFF1D1D23),
    surface_active = Color(0xFF15151A),
    text_primary = Color(0xFFECE7E1),
    text_secondary = Color(0xFFB0A9A1),
    text_tertiary = Color(0xFF948D85),
    text_disabled = Color(0xFF656059),
    text_on_fill = Color(0xFF000000),
    border_subtle = Color(0xFF17171C),
    border_default = Color(0xFF26262E),
    border_strong = Color(0xFF626270),
    focus_ring = Color(0xFF7AB8FF),
    success_text = Color(0xFF4AD3B0),
    success_fill = Color(0xFF2FBF9C),
    warning_text = Color(0xFFF0B040),
    warning_fill = Color(0xFFD99A2E),
    danger_text = Color(0xFFFF7A72),
    danger_fill = Color(0xFFD94F48),
    progress_text = Color(0xFF64B0FF),
    progress_fill = Color(0xFF2F7FD8),
    info_text = Color(0xFFA89AD0),
    info_fill = Color(0xFF8A7CB4),
    accent_text = Color(0xFFC98FA6),
    accent_fill = Color(0xFFB4738C),
    accent_hover = Color(0xFFBD8399),
    accent_active = Color(0xFFA86E82),
)

val EmberColors = RipsterColors(
    surface_canvas = Color(0xFF0B0908),
    surface_sunken = Color(0xFF0F0C0A),
    surface_raised = Color(0xFF15110D),
    surface_overlay = Color(0xFF1E1812),
    surface_hover = Color(0xFF271F18),
    surface_active = Color(0xFF1E1812),
    text_primary = Color(0xFFF2E8DD),
    text_secondary = Color(0xFFBDAE9F),
    text_tertiary = Color(0xFFA0907F),
    text_disabled = Color(0xFF6F6155),
    text_on_fill = Color(0xFF0B0908),
    border_subtle = Color(0xFF221B15),
    border_default = Color(0xFF332A20),
    border_strong = Color(0xFF78654E),
    focus_ring = Color(0xFF8FBCE8),
    success_text = Color(0xFF7FC9A4),
    success_fill = Color(0xFF3FA87E),
    warning_text = Color(0xFFEFA03A),
    warning_fill = Color(0xFFD98B20),
    danger_text = Color(0xFFF0806A),
    danger_fill = Color(0xFFD15540),
    progress_text = Color(0xFF79B0E0),
    progress_fill = Color(0xFF3F7FB8),
    info_text = Color(0xFFC4A8CC),
    info_fill = Color(0xFF9C82A8),
    accent_text = Color(0xFFDFA07A),
    accent_fill = Color(0xFFC07A4E),
    accent_hover = Color(0xFFD4915F),
    accent_active = Color(0xFFB3714A),
)

val SepiaColors = RipsterColors(
    surface_canvas = Color(0xFFF5EFE4),
    surface_sunken = Color(0xFFEFE7D9),
    surface_raised = Color(0xFFFFFCF5),
    surface_overlay = Color(0xFFF6EFE2),
    surface_hover = Color(0xFFF2EBDC),
    surface_active = Color(0xFFECE2D1),
    text_primary = Color(0xFF2C2620),
    text_secondary = Color(0xFF544537),
    text_tertiary = Color(0xFF665442),
    text_disabled = Color(0xFF8A7C68),
    text_on_fill = Color(0xFFFFFCF5),
    border_subtle = Color(0x1A463219),
    border_default = Color(0x33463219),
    border_strong = Color(0x99463219),
    focus_ring = Color(0xFF2A5F9E),
    success_text = Color(0xFF1B6B40),
    success_fill = Color(0xFF1B6B40),
    warning_text = Color(0xFF8A5A10),
    warning_fill = Color(0xFFB5730D),
    danger_text = Color(0xFFA8301F),
    danger_fill = Color(0xFFA8301F),
    progress_text = Color(0xFF2A5F9E),
    progress_fill = Color(0xFF2A5F9E),
    info_text = Color(0xFF5B4A9C),
    info_fill = Color(0xFF5B4A9C),
    accent_text = Color(0xFF8E4A66),
    accent_fill = Color(0xFF8E4A66),
    accent_hover = Color(0xFF7F4159),
    accent_active = Color(0xFF6D364C),
)

val NeonColors = RipsterColors(
    surface_canvas = Color(0xFF08070C),
    surface_sunken = Color(0xFF0B0910),
    surface_raised = Color(0xFF181420),
    surface_overlay = Color(0xFF201A2A),
    surface_hover = Color(0xFF2A2236),
    surface_active = Color(0xFF201A2A),
    text_primary = Color(0xFFF4EEF4),
    text_secondary = Color(0xFFB6A9BD),
    text_tertiary = Color(0xFF9A8BA3),
    text_disabled = Color(0xFF6B6276),
    text_on_fill = Color(0xFF08070C),
    border_subtle = Color(0xFF221B2C),
    border_default = Color(0xFF332A42),
    border_strong = Color(0xFF786594),
    focus_ring = Color(0xFFFF4D8F),
    success_text = Color(0xFF38E0A0),
    success_fill = Color(0xFF18C98A),
    warning_text = Color(0xFFFFD36B),
    warning_fill = Color(0xFFE0A83A),
    danger_text = Color(0xFFFF5C72),
    danger_fill = Color(0xFFE8405C),
    progress_text = Color(0xFF6AA8FF),
    progress_fill = Color(0xFF3F7FE0),
    info_text = Color(0xFFB98CFF),
    info_fill = Color(0xFF9564E0),
    accent_text = Color(0xFFFF4D8F),
    accent_fill = Color(0xFFFF4D8F),
    accent_hover = Color(0xFFFF6BA1),
    accent_active = Color(0xFFE8446F),
)
