package net.ripster.mobile.core.service

/**
 * Живые словари жанров, снятые с сервисов 05.09.2026.
 *
 * Это ЗАМЕР, а не выдумка: 22 названия Deezer (пришли по гео-локали на
 * болгарском), 22 у Apple, 190 у Яндекса вместе с не-музыкой и 161 слаг
 * ротора. Лежат отдельно от теста, чтобы было видно: проверка идёт по тому,
 * что сервисы отдают на самом деле, а не по подобранным примерам.
 */
object GenreVocabularies {
    val deezer = listOf(
        "African Music",
        "All",
        "Alternative",
        "Asian Music",
        "Blues",
        "Brazilian Music",
        "Classical",
        "Dance",
        "Electro",
        "Films/Games",
        "Folk",
        "Indian Music",
        "Jazz",
        "Kids",
        "Latin Music",
        "Metal",
        "Pop",
        "R&B",
        "Rap/Hip Hop",
        "Reggae",
        "Rock",
        "Soul & Funk",
    )

    val apple = listOf(
        "Alternative",
        "Blues",
        "Children's Music",
        "Christian",
        "Classical",
        "Country",
        "Dance",
        "Electronic",
        "Hip-Hop/Rap",
        "Holiday",
        "Jazz",
        "K-Pop",
        "Latin",
        "Metal",
        "Music",
        "Pop",
        "R&B/Soul",
        "Reggae",
        "Rock",
        "Singer/Songwriter",
        "Soundtrack",
        "Worldwide",
    )

    val yandex = listOf(
        "Action and Adventure",
        "African",
        "Alternative",
        "Alternative metal",
        "Ambient",
        "American",
        "Animated movies",
        "Anime",
        "Arabesque",
        "Arabic Pop",
        "Arabic Rap and Hip Hop",
        "Arabic children's music",
        "Arabic poetry",
        "Argentine Tango",
        "Armenian",
        "Audio Fairy Tales",
        "Azerbaijani",
        "Azerbaijani Pop Music",
        "Balkan",
        "Bass",
        "Bebop",
        "Big Band",
        "Biographies and memoirs",
        "Black metal",
        "Blues",
        "Bollywood",
        "Books Not In Russian",
        "Books for kids and teenagers",
        "Breakbeat",
        "Business",
        "Celtic",
        "Children's Poems",
        "Children’s Music",
        "Christmas-Repetoire",
        "Classical",
        "Contemporary Classical Music",
        "Contemporary Jazz",
        "Country",
        "Dabke",
        "Dance",
        "Death metal",
        "Disco",
        "Doom metal",
        "Drum and Bass",
        "Dub",
        "Dubstep",
        "EDM",
        "Eastern music",
        "Easy Listening",
        "Egyptian Pop",
        "Egyptian Rap and Hip-Hop",
        "Electronic",
        "Epic",
        "European",
        "Experimental",
        "Fantasy",
        "Fiction",
        "Folk",
        "Folk Rock",
        "From the Caucasus",
        "Funk",
        "Georgian",
        "Gothic",
        "Hard Rock",
        "Hardcore",
        "Healthy lifestyle",
        "Heavy metal",
        "History",
        "Horror and Supernatural",
        "House",
        "Hyperpop",
        "IDM",
        "In English",
        "Indie",
        "Industrial",
        "Iraqi Pop",
        "Islamic",
        "Israeli Pop",
        "Israeli Rap and Hip-Hop",
        "Israeli Rock",
        "J-Pop",
        "Jazz",
        "Jazz masterpieces",
        "Jewish",
        "K-Pop",
        "Kazakh Folk Music",
        "Kazakh Retro Pop",
        "Khaleeji Pop",
        "Khaleeji Rap & Hip-Hop",
        "Latin music",
        "Levant Pop",
        "Levant Rap & Hip-Hop",
        "Local Indie",
        "Lounge",
        "Love",
        "Lullabies",
        "Mahraganat",
        "Meditation",
        "Metal",
        "Metalcore",
        "Mix",
        "Mizrahi Music",
        "Moroccan Rap & Hip-Hop",
        "Moroccan pop",
        "Movie soundtracks",
        "Musicals",
        "Mysteries and thrillers",
        "Nature Sounds and City Noise",
        "New Age",
        "New Wave",
        "Non-Fiction",
        "Nu Metal",
        "Other",
        "Personal Development",
        "Philosophy and society",
        "Phonk",
        "Podcasts",
        "Poetry",
        "Pop",
        "Popular Science",
        "Post-Hardcore",
        "Post-Metal",
        "Post-Punk",
        "Post-Rock",
        "Progressive",
        "Progressive Rock",
        "Psychology and education",
        "Punjabi pop",
        "Punk",
        "Q-pop",
        "R&B",
        "Rap",
        "Rap and Hip-Hop",
        "Rap in Kazakh",
        "Rap in Uzbek",
        "Raï",
        "Reggae",
        "Reggaeton",
        "Retro Pop",
        "Rock",
        "Romance Music",
        "Russian",
        "Russian Chanson",
        "Russian Pop",
        "Russian Rap",
        "Russian Rock",
        "Science fiction",
        "Shelat",
        "Singer-Songwriter",
        "Ska",
        "Sludge",
        "Smooth Jazz",
        "Soul",
        "Soundtracks",
        "Spiritual",
        "Sports",
        "Stoner Rock",
        "Sufi music",
        "TV Series",
        "Talk shows",
        "Tarab",
        "Tatar",
        "Techno",
        "Technology",
        "Theater",
        "Thrash metal",
        "Traditional jazz",
        "Trance",
        "Trip Hop",
        "Turkish Alternative Music",
        "Turkish Classical Music",
        "Turkish Folk Music",
        "Turkish Pop",
        "Turkish Rap and Hip-Hop",
        "Turkish Rock",
        "UK Garage",
        "Ukrainian Rock",
        "Urdu hip-hop/trap",
        "Uzbek Folk Music",
        "Uzbek Pop Music",
        "Uzbek Retro Pop",
        "Video Games",
        "Vocal Jazz",
        "Vocal Music",
        "World Music",
        "World's Classical Masterpieces",
        "World's Classical Music",
        "Worldwide Children’s Music",
        "Worldwide Rock",
        "rock and roll",
    )

    val yandexRotor = listOf(
        "african",
        "allrock",
        "alternative",
        "alternativemetal",
        "ambientgenre",
        "amerfolk",
        "animated",
        "animemusic",
        "arabesquemusic",
        "arabickids",
        "arabicpop",
        "arabicrap",
        "argentinetango",
        "armenian",
        "azerbaijani",
        "azerbaijanpop",
        "balkan",
        "bard",
        "bassgenre",
        "bebopgenre",
        "bestofjazz",
        "bigbands",
        "blackmetal",
        "blues",
        "bollywood",
        "breakbeatgenre",
        "caucasian",
        "celtic",
        "children",
        "classical",
        "classicalmasterpieces",
        "classicalmusic",
        "classicmetal",
        "conjazz",
        "country",
        "dabkegenre",
        "dance",
        "deathmetal",
        "disco",
        "dnb",
        "doommetal",
        "dub",
        "dubstep",
        "eastern",
        "edmgenre",
        "egyptianpop",
        "egyptrap",
        "electronics",
        "epicmetal",
        "estrada",
        "eurofolk",
        "experimental",
        "fairytales",
        "films",
        "folk",
        "folkgenre",
        "folkmetal",
        "folkrock",
        "forchildren",
        "foreignbard",
        "foreignrap",
        "funk",
        "georgian",
        "gothicmetal",
        "hardcore",
        "hardrock",
        "house",
        "hyperpopgenre",
        "idmgenre",
        "indie",
        "industrial",
        "iraqipop",
        "israelipop",
        "israelirap",
        "israelirock",
        "japanesepop",
        "jazz",
        "jewish",
        "kazakhfolk",
        "kazakhrap",
        "kazestrada",
        "khaleejipop",
        "khaleejirap",
        "kpop",
        "latinfolk",
        "levantpop",
        "levantrap",
        "local-indie",
        "lounge",
        "lullaby",
        "mahraganat",
        "meditation",
        "metal",
        "metalcoregenre",
        "mizrahi",
        "modern",
        "moroccanpop",
        "moroccanrap",
        "musical",
        "naturesounds",
        "newage",
        "newwave",
        "numetal",
        "phonkgenre",
        "pop",
        "posthardcore",
        "postmetal",
        "postpunk",
        "postrock",
        "prog",
        "progmetal",
        "punk",
        "qazaqpop",
        "raigenre",
        "rap",
        "reggae",
        "reggaeton",
        "relax",
        "rnb",
        "rnr",
        "rock",
        "romances",
        "rusbards",
        "rusestrada",
        "rusfolk",
        "ruspop",
        "rusrap",
        "rusrock",
        "shanson",
        "shelatgenre",
        "ska",
        "sludgemetal",
        "smoothjazz",
        "soul",
        "soundtrack",
        "soviet",
        "sport",
        "stonerrock",
        "sufifolkgenre",
        "tarab",
        "tatar",
        "techno",
        "thrashmetal",
        "tradjazz",
        "trance",
        "triphopgenre",
        "turkishalternative",
        "turkishclassical",
        "turkishfolk",
        "turkishpop",
        "turkishrap",
        "turkishrock",
        "tvseries",
        "ukgaragegenre",
        "uzbekfolk",
        "uzbekpop",
        "uzbekrap",
        "uzretropop",
        "videogame",
        "vocal",
        "vocaljazz",
    )
}
